/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculatrice;


public class calculatrice extends javax.swing.JFrame {

    String numOne,numTwo;
    String sign ;
    public calculatrice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        panel1 = new java.awt.Panel();
        btn5 = new javax.swing.JButton();
        opEqual = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        opMinans = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        opPlus = new javax.swing.JButton();
        clean = new javax.swing.JButton();
        cleanAll = new javax.swing.JButton();
        modul = new javax.swing.JButton();
        opDivisen = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        dot = new javax.swing.JButton();
        opMultiple = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        opLog = new javax.swing.JLabel();
        result = new javax.swing.JLabel();
        checkbox1 = new java.awt.Checkbox();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(36, 52, 65));

        panel1.setBackground(new java.awt.Color(36, 52, 65));

        btn5.setBackground(new java.awt.Color(36, 52, 65));
        btn5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn5.setForeground(java.awt.Color.lightGray);
        btn5.setText("5");
        btn5.setBorder(null);
        btn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        opEqual.setBackground(new java.awt.Color(237, 128, 46));
        opEqual.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        opEqual.setForeground(new java.awt.Color(255, 255, 255));
        opEqual.setText("=");
        opEqual.setBorder(null);
        opEqual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opEqualActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(36, 52, 65));
        btn4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn4.setForeground(java.awt.Color.lightGray);
        btn4.setText("4");
        btn4.setBorder(null);
        btn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        opMinans.setBackground(new java.awt.Color(36, 52, 65));
        opMinans.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        opMinans.setForeground(new java.awt.Color(237, 128, 46));
        opMinans.setText("−");
        opMinans.setBorder(null);
        opMinans.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opMinans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opMinansActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(36, 52, 65));
        btn6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn6.setForeground(java.awt.Color.lightGray);
        btn6.setText("6");
        btn6.setBorder(null);
        btn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(36, 52, 65));
        btn3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn3.setForeground(java.awt.Color.lightGray);
        btn3.setText("3");
        btn3.setBorder(null);
        btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(36, 52, 65));
        btn2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn2.setForeground(java.awt.Color.lightGray);
        btn2.setText("2");
        btn2.setBorder(null);
        btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(36, 52, 65));
        btn1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn1.setForeground(java.awt.Color.lightGray);
        btn1.setText("1");
        btn1.setBorder(null);
        btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        opPlus.setBackground(new java.awt.Color(36, 52, 65));
        opPlus.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        opPlus.setForeground(new java.awt.Color(237, 128, 46));
        opPlus.setText("+");
        opPlus.setBorder(null);
        opPlus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opPlusActionPerformed(evt);
            }
        });

        clean.setBackground(new java.awt.Color(36, 52, 65));
        clean.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        clean.setForeground(new java.awt.Color(237, 128, 46));
        clean.setText("C");
        clean.setBorder(null);
        clean.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanActionPerformed(evt);
            }
        });

        cleanAll.setBackground(new java.awt.Color(36, 52, 65));
        cleanAll.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cleanAll.setForeground(new java.awt.Color(237, 128, 46));
        cleanAll.setText("AC");
        cleanAll.setBorder(null);
        cleanAll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cleanAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanAllActionPerformed(evt);
            }
        });

        modul.setBackground(new java.awt.Color(36, 52, 65));
        modul.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        modul.setForeground(new java.awt.Color(237, 128, 46));
        modul.setText("%");
        modul.setBorder(null);
        modul.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulActionPerformed(evt);
            }
        });

        opDivisen.setBackground(new java.awt.Color(36, 52, 65));
        opDivisen.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        opDivisen.setForeground(new java.awt.Color(237, 128, 46));
        opDivisen.setText("/");
        opDivisen.setBorder(null);
        opDivisen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opDivisen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opDivisenActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(36, 52, 65));
        btn7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn7.setForeground(java.awt.Color.lightGray);
        btn7.setText("7");
        btn7.setBorder(null);
        btn7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(36, 52, 65));
        btn8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn8.setForeground(java.awt.Color.lightGray);
        btn8.setText("8");
        btn8.setBorder(null);
        btn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(36, 52, 65));
        btn9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn9.setForeground(java.awt.Color.lightGray);
        btn9.setText("9");
        btn9.setBorder(null);
        btn9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        dot.setBackground(new java.awt.Color(36, 52, 65));
        dot.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        dot.setForeground(java.awt.Color.lightGray);
        dot.setText(".");
        dot.setBorder(null);
        dot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotActionPerformed(evt);
            }
        });

        opMultiple.setBackground(new java.awt.Color(36, 52, 65));
        opMultiple.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        opMultiple.setForeground(new java.awt.Color(237, 128, 46));
        opMultiple.setText("x");
        opMultiple.setBorder(null);
        opMultiple.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opMultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opMultipleActionPerformed(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(36, 52, 65));
        btn0.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn0.setForeground(java.awt.Color.lightGray);
        btn0.setText("0");
        btn0.setToolTipText("");
        btn0.setBorder(null);
        btn0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        opLog.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        opLog.setForeground(new java.awt.Color(204, 204, 204));
        opLog.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        opLog.setText("0");

        result.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        result.setForeground(new java.awt.Color(255, 255, 255));
        result.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        result.setText("0");

        checkbox1.setLabel("checkbox1");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel1Layout.createSequentialGroup()
                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(opMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel1Layout.createSequentialGroup()
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(opMinans, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel1Layout.createSequentialGroup()
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(opPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel1Layout.createSequentialGroup()
                            .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(dot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(opEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(opLog, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(clean, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cleanAll, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modul, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(opDivisen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(result)
                .addGap(10, 10, 10)
                .addComponent(opLog, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clean, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cleanAll, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modul, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opDivisen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opMinans, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int v1,v2,total;
    String operation;
    public void calc(){
        if(operation == "+"){
            total = v1 + v2;
        }
        if(operation == "-"){
            total = v1 - v2;
        }
        if(operation == "*"){
            total = v1 * v2;
        }
        else{
            
        }

        result.setText(""+total);
        v1 = total;
        numOne = total +"";
        numTwo = null;
        operation =null;
        
    }
    private void getInputs(String sign,String num){
        //clean
        if(sign == null && num ==null){
            result.setText("0");
            opLog.setText("0");
            numOne = null;
            numTwo = null;
            operation = null;
            return;
        }
        //add numbers
        if(sign==null){
            //get first number
          if (operation==null) {
            if(numOne==null&& num!=null){
                numOne = num;
            }
            else{
                numOne += num;
            }
            v1 = Integer.parseInt(numOne);
            
          }
          //get second number
          if (operation!=null) {
            if(numTwo==null&& num!=null){
                numTwo = num;
            }
            else{
                numTwo += num;
            }
            v2 = Integer.parseInt(numTwo);
      
          }
        }
        if(sign!=null){
            if (numOne==null && sign == "-"){
                numOne = "-";
            }
            if(numOne !=null && numTwo == null && operation != "="){
                operation = sign;
            }
            if(numOne!=null&& numTwo != null && operation != null){
              calc();
            }
        }

        opLog.setText((numOne==null?"":numOne)  +(operation==null&&operation!="="?"":operation) +(numTwo==null?"":numTwo));
        //numOne = Integer.parseInt(opLog.getText());

    }
    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        opLog.setText(opLog.getText()+"0");
        getInputs(null,"0");
        
    }//GEN-LAST:event_btn0ActionPerformed

    private void opMultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opMultipleActionPerformed
        // TODO add your handling code here:
        getInputs("*",null);
    }//GEN-LAST:event_opMultipleActionPerformed

    private void dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotActionPerformed
        // TODO add your handling code here:
        getInputs(null,".");
    }//GEN-LAST:event_dotActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        getInputs(null,"9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        getInputs(null,"8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        getInputs(null,"7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void opDivisenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opDivisenActionPerformed
        // TODO add your handling code here:
        getInputs("/",null);
    }//GEN-LAST:event_opDivisenActionPerformed

    private void modulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulActionPerformed
        // TODO add your handling code here:
        getInputs("%",null);
    }//GEN-LAST:event_modulActionPerformed

    private void cleanAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanAllActionPerformed
        // TODO add your handling code here:
        getInputs(null,null);
    }//GEN-LAST:event_cleanAllActionPerformed

    private void cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanActionPerformed
        // TODO add your handling code here:
        getInputs(null,null);
    }//GEN-LAST:event_cleanActionPerformed

    private void opPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opPlusActionPerformed
        // TODO add your handling code here:
        getInputs("+",null);
        
    }//GEN-LAST:event_opPlusActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        getInputs(null,"1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        getInputs(null,"2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        getInputs(null,"3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        getInputs(null,"6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void opMinansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opMinansActionPerformed
        // TODO add your handling code here:
        getInputs("-",null);
    }//GEN-LAST:event_opMinansActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        getInputs(null,"4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void opEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opEqualActionPerformed
        // TODO add your handling code here:
        getInputs("=",null);
        
    }//GEN-LAST:event_opEqualActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        getInputs(null,"5");
    }//GEN-LAST:event_btn5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculatrice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private java.awt.Checkbox checkbox1;
    private javax.swing.JButton clean;
    private javax.swing.JButton cleanAll;
    private javax.swing.JButton dot;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JButton modul;
    private javax.swing.JButton opDivisen;
    private javax.swing.JButton opEqual;
    private javax.swing.JLabel opLog;
    private javax.swing.JButton opMinans;
    private javax.swing.JButton opMultiple;
    private javax.swing.JButton opPlus;
    private java.awt.Panel panel1;
    private javax.swing.JLabel result;
    // End of variables declaration//GEN-END:variables
}
